curl -X POST -H "Content-Type: application/json" -d '{"id":1, "name": "Bulbasaur", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":2, "name": "Ivysaur", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":3, "name": "Venusaur", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":4, "name": "Charmander", "type": "Fire"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":5, "name": "Charmeleon", "type": "Fire"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":6, "name": "Charizard", "type": "Fire/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":7, "name": "Squirtle", "type": "Water"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":8, "name": "Wartortle", "type": "Water"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":9, "name": "Blastoise", "type": "Water"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":10, "name": "Caterpie", "type": "Bug"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":11, "name": "Metapod", "type": "Bug"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":12, "name": "Butterfree", "type": "Bug/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":13, "name": "Weedle", "type": "Bug/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":14, "name": "Kakuna", "type": "Bug/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":15, "name": "Beedrill", "type": "Bug/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":16, "name": "Pidgey", "type": "Normal/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":17, "name": "Pidgeotto", "type": "Normal/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":18, "name": "Pidgeot", "type": "Normal/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":19, "name": "Rattata", "type": "Normal"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":20, "name": "Raticate", "type": "Normal"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":21, "name": "Spearow", "type": "Normal/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":22, "name": "Fearow", "type": "Normal/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":23, "name": "Ekans", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":24, "name": "Arbok", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":25, "name": "Pikachu", "type": "Electric"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":26, "name": "Raichu", "type": "Electric"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":27, "name": "Sandshrew", "type": "Ground"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":28, "name": "Sandslash", "type": "Ground"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":29, "name": "Nidoran♀", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":30, "name": "Nidorina", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":31, "name": "Nidoqueen", "type": "Poison/Ground"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":32, "name": "Nidoran♂", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":33, "name": "Nidorino", "type": "Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":34, "name": "Nidoking", "type": "Poison/Ground"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":35, "name": "Clefairy", "type": "Fairy"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":36, "name": "Clefable", "type": "Fairy"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":37, "name": "Vulpix", "type": "Fire"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":38, "name": "Ninetales", "type": "Fire"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":39, "name": "Jigglypuff", "type": "Normal/Fairy"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":40, "name": "Wigglytuff", "type": "Normal/Fairy"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":41, "name": "Zubat", "type": "Poison/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":42, "name": "Golbat", "type": "Poison/Flying"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":43, "name": "Oddish", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":44, "name": "Gloom", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":45, "name": "Vileplume", "type": "Grass/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":46, "name": "Paras", "type": "Bug/Grass"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":47, "name": "Parasect", "type": "Bug/Grass"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":48, "name": "Venonat", "type": "Bug/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":49, "name": "Venomoth", "type": "Bug/Poison"}' http://localhost:8080/api/pokemon
curl -X POST -H "Content-Type: application/json" -d '{"id":50, "name": "Diglett", "type": "Ground"}' http://localhost:8080/api/pokemon